steps:
  # Build and push client image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:$SHORT_SHA'
      - '-f'
      - 'client/Dockerfile'
      - '.'
    id: 'build-client'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:$SHORT_SHA']
    id: 'push-client'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:$SHORT_SHA'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:latest'
    id: 'tag-client-latest'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:latest']
    id: 'push-client-latest'

  # Build and push server image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-server:$SHORT_SHA'
      - '-f'
      - 'server/Dockerfile'
      - '.'
    id: 'build-server'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-server:$SHORT_SHA']
    id: 'push-server'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-server:$SHORT_SHA'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-server:latest'
    id: 'tag-server-latest'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-server:latest']
    id: 'push-server-latest'

  # Build and push worker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-worker:$SHORT_SHA'
      - '-f'
      - 'worker/Dockerfile'
      - '.'
    id: 'build-worker'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-worker:$SHORT_SHA']
    id: 'push-worker'


  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-worker:$SHORT_SHA'
      - 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-worker:latest'
    id: 'tag-worker-latest'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-worker:latest']
    id: 'push-worker-latest'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=multi-k8s'
    id: 'apply-k8s-manifests'


  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/client-deployment'
      - 'client=europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:latest'
      - '-n'
      - 'default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=multi-k8s'
    id: 'deploy-client'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/server-deployment'
      - 'server=europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-server:latest'
      - '-n'
      - 'default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=multi-k8s'
    id: 'deploy-server'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/worker-deployment'
      - 'worker=europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-worker:latest'
      - '-n'
      - 'default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=multi-k8s'
    id: 'deploy-worker'

timeout: '1800s'
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
