apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: europe-docker.pkg.dev/$PROJECT_ID/k8s-multi-app-repo/multi-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000